- name: Upgrade all system packages
  hosts: all
  serial: 1
  tasks:
    - name: Ugrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Wait for all nodes to be ready
      shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
